# Generated by Django 5.2.10 on 2026-01-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Abierto', max_length=50)),
                ('asignado_a', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
